package org.stonlexx.packetwrapper.api.packet.server;

import com.comphenix.protocol.PacketType;
import org.stonlexx.packetwrapper.api.packet.WrapperPacket;

public interface WrapperLoginServerCustomPayload extends WrapperPacket {
    PacketType TYPE = PacketType.Login.Server.CUSTOM_PAYLOAD;

    /**
     * Retrieve Message ID.
     * <p>
     * Notes: generated by the server - should be unique to the connection.
     *
     * @return The current Message ID
     */
    int getMessageId();

    /**
     * Set Message ID.
     *
     * @param value - new value.
     */
    void setMessageId(int value);

    // Cannot find type for b
    // Cannot find type for b
}
