package org.stonlexx.packetwrapper.v1_15.packet.server;

import com.comphenix.protocol.events.PacketContainer;
import org.stonlexx.packetwrapper.api.packet.MinecraftPacket;
import org.stonlexx.packetwrapper.api.packet.server.WrapperLoginServerCustomPayload;

import org.stonlexx.packetwrapper.api.packet.server.WrapperLoginServerCustomPayload;

public class WrapperLoginServerCustomPayload1_15 
        extends MinecraftPacket
        implements WrapperLoginServerCustomPayload {

    public WrapperLoginServerCustomPayload1_15() {
        super(new PacketContainer(TYPE), TYPE);
        container.getModifier().writeDefaults();
    }
    
    public WrapperLoginServerCustomPayload1_15(PacketContainer packet) {
        super(packet, TYPE);
    }
    
    /**
     * Retrieve Message ID.
     * <p>
     * Notes: generated by the server - should be unique to the connection.
     * @return The current Message ID
     */
    public int getMessageId() {
        return container.getIntegers().read(0);
    }
    
    /**
     * Set Message ID.
     * @param value - new value.
     */
    public void setMessageId(int value) {
        container.getIntegers().write(0, value);
    }
    
    // Cannot find type for b
    // Cannot find type for b
}
